**GROUP 4**

1. Loice Nguku

2. Karimot Adegoke

3. Mary Kama

4. Nancy Okara

5. Oluwatosin George

6. Modupeoluwa Adedeji

7. Monsurat Jimoh

8. Obughikem Nwanya

9. Olajumoke Oladele

***Andriod App Market Analysis on Google Playstore***

1. Read-in Dataset

In [ ]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from datetime import datetime

In [ ]:
# loading the dataset into pandas dataframe
apps_with_duplicates = pd.read_csv('googleplaystore.csv')

In [ ]:
apps_with_duplicates

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite â€“ FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10836,Sya9a Maroc - FR,FAMILY,4.5,38,53M,"5,000+",Free,0,Everyone,Education,"July 25, 2017",1.48,4.1 and up
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4,3.6M,100+,Free,0,Everyone,Education,"July 6, 2018",1.0,4.1 and up
10838,Parkinson Exercices FR,MEDICAL,NaN,3,9.5M,"1,000+",Free,0,Everyone,Medical,"January 20, 2017",1.0,2.2 and up
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,Varies with device,"1,000+",Free,0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19M,"10,000,000+",Free,0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device

# New Section

2. Remove Duplicates

In [ ]:
#df = apps_with_duplicates.drop([10474, inplace=True])

In [ ]:
apps_with_duplicates.shape

(10841, 13)

In [ ]:
 # check for duplicate in the datas
apps_with_duplicates.duplicated().sum()

483

In [ ]:
# drop the duplicates
apps = apps_with_duplicates.drop_duplicates()
# Print the total number of apps
print('Total number of apps in the dataset = ', len(apps))
# Have a look at a random sample of 5 rows
apps.sample(5)

Total number of apps in the dataset =  10358

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
1692,Shooting King,GAME,4.4,257724,69M,"10,000,000+",Free,0,Everyone 10+,Sports,"May 25, 2018",1.4.2,4.0.3 and up
10543,FK Radnicki Nis,SPORTS,NaN,1,26M,50+,Free,0,Everyone,Sports,"February 19, 2018",1.0,4.1 and up
9985,Doll House Design & Decoration 2: Girls House ...,FAMILY,3.9,2338,45M,"100,000+",Free,0,Everyone,Simulation,"May 29, 2018",1.1,4.1 and up
3639,Yahoo Weather,WEATHER,4.4,1312037,Varies with device,"10,000,000+",Free,0,Everyone,Weather,"August 1, 2018",Varies with device,Varies with device
1089,WiseBanyan - Invest For Free,FINANCE,4.2,257,44M,"10,000+",Free,0,Everyone,Finance,"July 31, 2018",2.2.12,4.4W and up

3. DATA CLEANING

In [ ]:
# List of characters to remove
chars_to_remove = ["+",",","$"]
# List of column names to clean
cols_to_clean = ["Installs","Price"]
# Loop for each column in cols_to_clean
for col in cols_to_clean:
    # Loop for each char in chars_to_remove
    for char in chars_to_remove:
        # Replace the character with an empty string
        apps[col] = apps[col].apply(lambda x: x.replace(char, ''))
        print(apps.info())

<class 'pandas.core.frame.DataFrame'>
Int64Index: 10358 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10358 non-null  object
 1   Category        10358 non-null  object
 2   Rating          8893 non-null   float64
 3   Reviews         10358 non-null  object
 4   Size            10358 non-null  object
 5   Installs        10358 non-null  object
 6   Type            10357 non-null  object
 7   Price           10358 non-null  object
 8   Content Rating  10357 non-null  object
 9   Genres          10358 non-null  object
 10  Last Updated    10358 non-null  object
 11  Current Ver     10350 non-null  object
 12  Android Ver     10355 non-null  object
dtypes: float64(1), object(12)
memory usage: 1.1+ MB
None
<class 'pandas.core.frame.DataFrame'>
Int64Index: 10358 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10358 non-null  object
 1   Category        10358 non-null  object
 2   Rating          8893 non-null   float64
 3   Reviews         10358 non-null  object
 4   Size            10358 non-null  object
 5   Installs        10358 non-null  object
 6   Type            10357 non-null  object
 7   Price           10358 non-null  object
 8   Content Rating  10357 non-null  object
 9   Genres          10358 non-null  object
 10  Last Updated    10358 non-null  object
 11  Current Ver     10350 non-null  object
 12  Android Ver     10355 non-null  object
dtypes: float64(1), object(12)
memory usage: 1.1+ MB
None
<class 'pandas.core.frame.DataFrame'>
Int64Index: 10358 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10358 non-null  object
 1   Category        10358 non-null  object
 2   Rating          8893 non-null   float64
 3   Reviews         10358 non-null  object
 4   Size            10358 non-null  object
 5   Installs        10358 non-null  object
 6   Type            10357 non-null  object
 7   Price           10358 non-null  object
 8   Content Rating  10357 non-null  object
 9   Genres          10358 non-null  object
 10  Last Updated    10358 non-null  object
 11  Current Ver     10350 non-null  object
 12  Android Ver     10355 non-null  object
dtypes: float64(1), object(12)
memory usage: 1.1+ MB
None
<class 'pandas.core.frame.DataFrame'>
Int64Index: 10358 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10358 non-null  object
 1   Category        10358 non-null  object
 2   Rating          8893 non-null   float64
 3   Reviews         10358 non-null  object
 4   Size            10358 non-null  object
 5   Installs        10358 non-null  object
 6   Type            10357 non-null  object
 7   Price           10358 non-null  object
 8   Content Rating  10357 non-null  object
 9   Genres          10358 non-null  object
 10  Last Updated    10358 non-null  object
 11  Current Ver     10350 non-null  object
 12  Android Ver     10355 non-null  object
dtypes: float64(1), object(12)
memory usage: 1.1+ MB
None
<class 'pandas.core.frame.DataFrame'>
Int64Index: 10358 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10358 non-null  object
 1   Category        10358 non-null  object
 2   Rating          8893 non-null   float64
 3   Reviews         10358 non-null  object
 4   Size            10358 non-null  object
 5   Installs        10358 non-null  object
 6   Type            10357 non-null  object
 7   Price           10358 non-null  object
 8   Content Rating  10357 non-null  object
 9   Genres          10358 non-null  object
 10  Last Updated    10358 non-null  object
 11  Current Ver     10350 non-null  object
 12  Android Ver     10355 non-null  object
dtypes: float64(1), object(12)
memory usage: 1.1+ MB
None
<class 'pandas.core.frame.DataFrame'>
Int64Index: 10358 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10358 non-null  object
 1   Category        10358 non-null  object
 2   Rating          8893 non-null   float64
 3   Reviews         10358 non-null  object
 4   Size            10358 non-null  object
 5   Installs        10358 non-null  object
 6   Type            10357 non-null  object
 7   Price           10358 non-null  object
 8   Content Rating  10357 non-null  object
 9   Genres          10358 non-null  object
 10  Last Updated    10358 non-null  object
 11  Current Ver     10350 non-null  object
 12  Android Ver     10355 non-null  object
dtypes: float64(1), object(12)
memory usage: 1.1+ MB
None

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.

In [ ]:
#after going true the data i saw a cell with the data called Free in row 10474 and column Installs and Price
apps= apps.drop(apps[apps.Installs == 'Free'].index)
apps= apps.drop(apps[apps.Price == 'Everyone'].index)

In [ ]:
# Changing Data 

import numpy as np

# Convert Installs to float data type
apps['Installs'] = apps['Installs'].astype('float')
# Convert Price to float data type
apps['Price'] = apps['Price'].astype('float')
# Checking dtypes of the apps dataframe
apps.dtypes

In [ ]:
apps.sample(10)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
3241,Moto Voice,TOOLS,4.1,33216,Varies with device,10000000.0,Free,0.0,Everyone,Tools,"June 5, 2018",Varies with device,Varies with device
8830,DS Tower Defence,GAME,3.2,768,1.4M,100000.0,Free,0.0,Everyone,Arcade,"June 5, 2013",1.0,1.5 and up
5691,Avatar Musik,GAME,3.8,159063,85M,1000000.0,Free,0.0,Everyone,Music,"February 9, 2018",0.8.0,4.0 and up
6391,BK Arogyam Task Track,BUSINESS,5.0,8,3.7M,100.0,Free,0.0,Everyone,Business,"June 5, 2018",1.1.1,4.1 and up
820,Edmodo,EDUCATION,4.1,200058,18M,10000000.0,Free,0.0,Everyone,Education,"July 20, 2018",9.12.5,4.0.3 and up
10698,FO PSA Sept-Fons,COMMUNICATION,NaN,2,15M,100.0,Free,0.0,Everyone,Communication,"March 22, 2018",1.0,4.1 and up
3760,Podcast App: Free & Offline Podcasts by Player FM,NEWS_AND_MAGAZINES,4.6,66384,19M,1000000.0,Free,0.0,Teen,News & Magazines,"July 25, 2018",4.1.0.72,4.0 and up
10357,RÃ­os de Fe,LIFESTYLE,5.0,141,15M,1000.0,Free,0.0,Everyone,Lifestyle,"March 24, 2018",1.8,4.1 and up
449,"Truecaller: Caller ID, SMS spam blocking & Dialer",COMMUNICATION,4.5,7820209,Varies with device,100000000.0,Free,0.0,Everyone,Communication,"August 1, 2018",Varies with device,Varies with device
6601,bp e-store,BOOKS_AND_REFERENCE,4.4,52,2.2M,1000.0,Free,0.0,Everyone,Books & Reference,"January 15, 2016",2.0.7,4.0 and up

In [ ]:
# Saw 'varies with device' is present under the 'Size' and a Character 'M' after the sizes

#stripping to remove M 
apps['Size'] = apps['Size'].str.strip('M')
apps.drop(apps[apps.Size == 'Varies with device'].index)
apps.drop(apps[apps.Rating.isnull()].index)

In [ ]:
apps

4. EXPLORING APP CATEGORIES

In [ ]:
import plotly
plotly.offline.init_notebook_mode(connected=True)
import plotly.graph_objs as go

# Print the total number of unique categories
num_categories = len(apps['Category'].unique())
#print('Number of categories = ', num_categories)

# Count the number of apps in each 'Category'. 
num_apps_in_category = apps['Category'].value_counts()

# Sort num_apps_in_category in descending order based on the count of apps in each category
sorted_num_apps_in_category = num_apps_in_category.sort_values(ascending=False)

data = [go.Bar(
        x = num_apps_in_category.index, # index = category name
        y = num_apps_in_category.values, # value = count
)]

plotly.offline.iplot(data)

5. DISTRIBUTION OF APP RATINGS

In [ ]:
# Average rating of apps
avg_app_rating = apps['Rating'].mean()
print('Average app rating = ', avg_app_rating)

# Distribution of apps according to their ratings
data = [go.Histogram(
        x = apps['Rating']
)]

# Vertical dashed line to indicate the average app rating
layout = {'shapes': [{
              'type' :'line',
              'x0': avg_app_rating,
              'y0': 0,
              'x1': avg_app_rating,
              'y1': 1000,
              'line': { 'dash': 'dashdot'}
          }]
          }

plotly.offline.iplot({'data': data, 'layout': layout})

6.SIZE AND PRICE OF AN APP

In [ ]:
%matplotlib inline
import seaborn as sns
sns.set_style("darkgrid")
import warnings
warnings.filterwarnings("ignore")

# Select rows where both 'Rating' and 'Size' values are present (ie. the two values are not null)
apps_with_size_and_rating_present = apps.dropna()

# Subset for categories with at least 250 apps
large_categories = apps_with_size_and_rating_present.groupby('Category').filter(lambda x: len(x) >= 250)

# Plot size vs. rating
plt1 = sns.jointplot(x = large_categories['Size'], y = large_categories['Rating'])

# Select apps whose 'Type' is 'Paid'
paid_apps = apps_with_size_and_rating_present[apps_with_size_and_rating_present['Type'] =="Paid"]

# Plot price vs. rating
plt2 = sns.jointplot(x = paid_apps['Price'], y = paid_apps['Rating'])

7. Relation between app category and app price

In [ ]:
import matplotlib.pyplot as plt
fig, ax = plt.subplots()
fig.set_size_inches(15, 8)

# Select a few popular app categories
popular_app_cats = apps[apps.Category.isin(['GAME', 'FAMILY', 'PHOTOGRAPHY',
                                            'MEDICAL', 'TOOLS', 'FINANCE',
                                            'LIFESTYLE','BUSINESS'])]

# Examine the price trend by plotting Price vs Category
ax = sns.stripplot(x = popular_app_cats['Price'], y = popular_app_cats['Category'], jitter=True, linewidth=1)
ax.set_title('App pricing trend across categories')

# Apps whose Price is greater than 200
apps_above_200 = popular_app_cats[['Category', 'App', 'Price']][popular_app_cats['Price']>200]
apps_above_200

8.Filter out "junk" apps

In [ ]:
# Select apps priced below $100
apps_under_100 = popular_app_cats[popular_app_cats['Price']<100]

fig, ax = plt.subplots()
fig.set_size_inches(15, 8)

# Examine price vs category with the authentic apps (apps_under_100)
ax = sns.stripplot(x = 'Price', y = 'Category', data = apps_under_100, jitter = True, linewidth = 1)
ax.set_title('App pricing trend across categories after filtering for junk apps')

9.  Popularity of paid apps vs free apps

In [ ]:
trace0 = go.Box(
    # Data for paid apps
    y = apps[apps['Type'] == 'Paid']['Installs'],
    name = 'Paid'
)

trace1 = go.Box(
    # Data for free apps
    y = apps[apps['Type'] == 'Free']['Installs'],
    name = 'Free'
)

layout = go.Layout(
    title = "Number of downloads of paid apps vs. free apps",
    yaxis = dict(title = "Log number of downloads",
                type = 'log',
                autorange = True)
)

# Add trace0 and trace1 to a list for plotting
data = [trace0, trace1]
plotly.offline.iplot({'data': data, 'layout': layout})

10. Sentiment analysis of user reviews

In [ ]:
# Load user_reviews.csv
reviews= pd.read_csv('/content/googleplaystore.csv')

# Join the two dataframes
merged= pd.merge(apps, reviews, on= "App", how = "inner")

# Drop NA values from Sentiment and Review columns
merged = merged.dropna(subset = ["Sentiment",'Reviews"], inplace)

sns.set_style('ticks')
fig, ax = plt.subplots()
fig.set_size_inches(11, 8)

# User review sentiment polarity for paid vs. free apps
ax = sns.boxplot(x = "Type", y = "Sentiment_Polarity" , data = merged)
ax.set_title('Sentiment Polarity Distribution')